/**
 * BandChat Website Template — Site Configuration
 *
 * This file is auto-generated by BandChat when a band deploys their website.
 * Do not edit manually — changes will be overwritten on the next deploy.
 *
 * The BandChat server writes this file via the GitHub API with the band's
 * specific configuration (name, colors, features, etc.)
 */

export default {
  // ── Band Identity ──────────────────────────────────────────────
  band: {
    name: 'My Band',
    tagline: 'Our music, our stage',
    description: 'Welcome to our band website, powered by BandChat.',
    location: '',
    genre: '',
    founded: null,
    story: [],
  },

  // ── Domain & Contact ───────────────────────────────────────────
  domain: '',
  emails: {
    info: '',
    privacy: '',
  },

  // ── Social Media ───────────────────────────────────────────────
  social: [],

  // ── Template (genre theme) ─────────────────────────────────────
  template: 'covers',

  // ── Theme ──────────────────────────────────────────────────────
  theme: {
    primaryAccent: '#ff2d78',
    secondaryAccent: '#00c2ff',
  },

  // ── Images ─────────────────────────────────────────────────────
  images: {
    logo: null,
    ogImage: null,
    favicon: '/images/icons/favicon.svg',
    heroImages: [],
  },

  // ── Features (toggle pages on/off) ─────────────────────────────
  features: {
    songs: true,
    archive: true,
    setlists: false,
    timeline: false,
    media: true,
    stats: true,
    blog: false,
    community: false,
    merch: false,
    trivia: false,
    songRequests: false,
    aiAgents: false,
  },

  // ── SEO ────────────────────────────────────────────────────────
  seo: {
    title: 'My Band | Official Website',
    description: 'Official band website powered by BandChat.',
  },

  // ── AI Agents (disabled by default) ────────────────────────────
  agents: null,
};
