// Auto-generated by BandChat — do not edit manually
export default {
  "seo": {
    "title": "No Code | Official Website",
    "description": "Pearl Jam, Grunge, Live Music"
  },
  "band": {
    "name": "No Code",
    "genre": "Pearl Jam",
    "founded": 2025,
    "tagline": "Tokyo's Pearl Jam Tribute Band",
    "location": "Tokyo, Japan",
    "description": "Keeping Grunge Alive Since 2025"
  },
  "genre": "Pearl Jam",
  "theme": {
    "template": "grunge",
    "primaryAccent": "#ff3250",
    "secondaryAccent": "#ffc800"
  },
  "emails": {
    "info": ""
  },
  "images": {
    "logo": null,
    "heroImages": [
      "https://pub-84ab70b370d7498390626d5f77c82f60.r2.dev/images/60baf284-f9ac-48e9-8646-45774bdf4a06.jpg"
    ],
    "mediaImages": []
  },
  "social": [
    {
      "url": "https://www.instagram.com/no_code_tokyo?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
      "label": "Instagram",
      "platform": "instagram"
    }
  ],
  "founded": 2025,
  "tagline": "Tokyo's Pearl Jam Tribute Band",
  "bandName": "No Code",
  "features": {
    "blog": false,
    "media": true,
    "merch": false,
    "songs": true,
    "stats": true,
    "trivia": true,
    "archive": true,
    "setlists": true,
    "timeline": true,
    "community": false,
    "songRequests": false
  },
  "location": "Tokyo, Japan",
  "template": "grunge",
  "description": "Keeping Grunge Alive Since 2025",
  "socialLinks": {
    "spotify": "",
    "youtube": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/no_code_tokyo?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="
  },
  "contactEmail": "",
  "customizations": {
    "customLinks": [],
    "youtubeUrls": []
  },
  "useCustomizations": true
};
